Revert "usb: gadget: configfs: fix concurrent issue between composite APIs"
This reverts commit aa919ef9a34b29e79b7a3fef79df7165376a4cf1.

We don't have configfs_composite_disconnect and configfs_composite_setup.

Fix compile error:

../drivers/usb/gadget/configfs.c:1525:12: error: unused function 'configfs_composite_setup' [-Werror,-Wunused-function]
static int configfs_composite_setup(struct usb_gadget *gadget,
           ^
../drivers/usb/gadget/configfs.c:1550:13: error: unused function 'configfs_composite_disconnect' [-Werror,-Wunused-function]
static void configfs_composite_disconnect(struct usb_gadget *gadget)
            ^
2 errors generated.