drivers: slim-msm-ngd: Fix unused variable 'dev'
    ../drivers/slimbus/slim-msm-ngd.c:1030:24: error: unused variable 'dev' [-Werror,-Wunused-variable]
            struct msm_slim_ctrl *dev = slim_get_ctrldata(ctrl);
                                  ^
    1 error generated.