drivers: glink_loopback_server: Fix unused variable 'tx_done_ch_info'
../drivers/soc/qcom/glink_loopback_server.c:810:18: error: unused variable 'tx_done_ch_info' [-Werror,-Wunused-variable]
        struct ch_info *tx_done_ch_info = (struct ch_info *)priv;
                        ^
1 error generated.