kernel: printk: Fix unused variable 'ret'
Fix after add commit "kernel/printk: Convert to hotplug state machine" da5ba4a08e9b6c97038f193a88fa8d2afc72c286

../kernel/printk/printk.c:2787:6: error: unused variable 'ret' [-Werror,-Wunused-variable]
        int ret;
            ^
1 error generated.