kernel: fair: remove unused variable "spare_cap"
../kernel/sched/fair.c:6958:7: error: unused variable 'spare_cap'
      [-Werror,-Wunused-variable]
        long spare_cap, most_spare_cap = 0;
             ^
1 error generated.